function:
  study_mapping: False
  check_for_missing_modules: True
  plot_lpGBTLoads: False
  plot_ModuleLoads: False               

print_level: 0
output_dir: .

study_mapping:
  MappingFile: data/FeMappingV7.txt
  CMSSW_ModuleHists: dataROverZHistograms_v11_relval_neutrino_gun_20200611.root

  #Algorithms for minimisation:
  #'random_hill_climb', 'simulated_annealing', 'save_root'
  algorithm: random_hill_climb

  #initial state configuation:
  #'random', 'example', 'data/bundles_job_best_neutrinogun_200617.npy'
  initial_state: random

  random_seed: ~
  max_iterations: 100000 

  #Definition of a minigroup:
  #'bylayer_silicon_seprated', 'bylayer', 'minimal'
  minigroup_type: 'minimal'

  include_errors_in_chi2: False

corrections:
  ldmToHdmModuleCorrectionFile: 'data/different_moduleType_HDMInMappingFile_linkMapping.txt'
  ldmToHdmCorrectionType : 'FixedOcc'
  nTCCorrectionFile: 'data/different_nTCs_linkMapping.txt'

check_for_missing_modules:
  inCMSSW: True
  inMappingFile: True
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"

plot_lpGBTLoads:
  MappingFile: data/FeMappingV7.txt
  # V11
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"
  # V10
  # CMSSW_Silicon: "data/average_tcs_sil_v10_qg_20200331.csv"
  # CMSSW_Scintillator: "data/average_tcs_scin_v10_qg_20200331.csv"

plot_ModuleLoads:
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"
