function:
  study_mapping: True
  check_for_missing_modules: False
  plot_lpGBTLoads: False
  plot_ModuleLoads: False
  produce_AllocationFile: False               
  produce_nTCsPerModuleHists: False
  produce_JsonMappingFile: False
  
print_level: 0
output_dir: .

study_mapping:
  MappingFile: data/FeMappingTpgV7.txt
  CMSSW_ModuleHists: data/ROverZHistograms_v11_relval_ttbar_20210729.root
  TowerMappingFile: data/tower_per_module-20210517-Silic8-Scint16.txt
  TowerPhiSplit: [6,15]

  #Algorithms for minimisation:
  #'random_hill_climb', 'simulated_annealing', 'save_root'
  algorithm: random_hill_climb

  #initial state configuation:
  #'random', 'data/bundles_example-pickle-tpgv7-14fpgas.npy'
  initial_state: random

  random_seed: ~
  max_iterations: 200000
  #Set max_calls if you know the exact number of calls needed to reproduce a certain mapping configuration
  max_calls: ~

  #Definition of a minigroup:
  #'bylayer_silicon_seprated', 'bylayer', 'minimal'
  minigroup_type: 'minimal'

  #Options for use in the chi2 function
  chi2:
    include_errors_in_chi2: True
    include_max_modules_in_chi2: True
    include_max_towers_in_chi2: True
    max_modules_weighting_factor: 30000
    max_towers_weighting_option: 2 #option 1 uses max directly, option 2 uses it within a step-like function
    max_towers_step_point: 380 #The value of max_towers above which the chi2 increases quickly when using option 2
    max_towers_weighting_factor: 30000
    weight_bins_proportionally: True #divide the chi2 in each r/z bin by the bin content 

  phisplit:
    #How to split in phi, either 'per_roverz_bin' (midpoint splits taken from CMSSW_ModuleHists file) or 'fixed'
    #If 'fixed' need to provide split values in degrees,
    #i.e. fixed point in phi at which the split should occur: 'phidivisionX_fixvalue_min' and #phidivisionY_fixvalue_max'
    #'per_roverz_bin', 'fixed'
    type: per_roverz_bin
    phidivisionX_fixvalue_min: 55 #degrees
    phidivisionY_fixvalue_max: 55 #degrees

  corrections:
    nTCCorrectionFile: 'data/different_nTCs_linkMapping.txt'
  
  fpgas:
    #Number of stage 1 FPGAs covering a sector
    nBundles: 14
    #Maximum number of lpGBT inputs to each FPGA
    maxInputs: 120

check_for_missing_modules:
  inCMSSW: True
  inMappingFile: True
  MappingFile: data/FeMappingTpgV7.txt
  CMSSW_Silicon: "data/average_tcs/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs/average_tcs_scin_v11_relval_ttbar_20200611.csv"

plot_lpGBTLoads:
  MappingFile: data/FeMappingTpgV7.txt
  # V11
  CMSSW_Silicon: "data/average_tcs/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs/average_tcs_scin_v11_relval_ttbar_20200611.csv"
  # V10
  # CMSSW_Silicon: "data/average_tcs/average_tcs_sil_v10_qg_20200331.csv"
  # CMSSW_Scintillator: "data/average_tcs/average_tcs_scin_v10_qg_20200331.csv"

plot_ModuleLoads:
  MappingFile: data/FeMappingTpgV7.txt
  CMSSW_Silicon: "data/average_tcs/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs/average_tcs_scin_v11_relval_ttbar_20200611.csv"

produce_AllocationFile:
  allocation: data/bundles_example-pickle-tpgv7-14fpgas.npy
  file_name: 'allocation.txt'

produce_nTCsPerModuleHists:
  allocation: data/bundles_example-pickle-tpgv7-14fpgas.npy
  CMSSW_ModuleHists: data/nTCs_v11_relval_ttbar_20200814.root

produce_JsonMappingFile:
  allocation: data/bundles_example-pickle-tpgv7-14fpgas.npy
  output_name: hgcal_trigger_link_mapping.json
  # disconnected_modules: data/test_triggergeom.root #optional root file listing disconnected modules