function:
  checkFluctuations: False
  plot_MeanMax: True
  plot_Truncation: True
  studyTruncationOptions: False
  
print_level: 0
output_dir: .

corrections:
  ldmToHdmModuleCorrectionFile: 'data/different_moduleType_HDMInMappingFile_linkMapping.txt'
  ldmToHdmCorrectionType: 'FixedOcc'
  nTCCorrectionFile: 'data/different_nTCs_linkMapping.txt'

checkFluctuations:  
  beginEvent: -1
  endEvent: -1
  initial_state: bundles_job_best_neutrinogun_200617.npy
  cmsswNtuple: data/small_v11_relval_ttbar_200611.root
  outputName: alldata_neutrino_gun_2006022
  mappingFile: data/FeMappingV7.txt
  weight_by_tcPt: False

  phisplit:
    #How to split in phi, if 'per_roverz_bin' need to provide a root splitfile
    #If 'fixed' need to provide split values in degrees,
    #i.e. fixed point in phi at which the split should occur: 'RegionA_fixvalue_min' and #RegionB_fixvalue_max'
    #'per_roverz_bin', 'fixed'
    type: per_roverz_bin
    
    splitfile: data/ROverZHistograms_v11_relval_ttbar_20200716.root
    RegionA_fixvalue_min: 55 #degrees
    RegionB_fixvalue_max: 55 #degrees
  
plot_MeanMax:
  eventData: data/alldata_neutrino_gun_2006022.txt
  includePhi60: True
  
plot_Truncation:
  eventData: data/alldata_neutrino_gun_2006022.txt
  includePhi60: True

studyTruncationOptions:
  eventData: data/alldata_neutrino_gun_2006022.txt
  includePhi60: True